import { requireCustomer,getSupabase,loadPlans,loadSettings,uploadFile,getActiveSubscription,getDemoInvitationById } from './supabase.js';
import { fallbackPlans } from './data.js';
import { initI18n,getLang,t } from './i18n.js';
import { $ } from './utils.js';
initI18n();
const q=new URLSearchParams(location.search);const planSlug=q.get('plan'),invitationId=q.get('invitation');let plan,invite,settings,user;
function money(n){return `${Number(n||0).toLocaleString('en-US')} ${settings?.currency||'EGP'}`}
function render(){const l=getLang();if(plan)$('#checkoutPlan').innerHTML=`<div><small>${plan.name_en}</small><strong>${l==='ar'?plan.name_ar:plan.name_en}</strong></div><div style="text-align:end"><small>${l==='ar'?'الإجمالي':'Total'}</small><strong>${money(plan.price)}</strong></div>`;if(invite)$('#checkoutInvite').textContent=`${invite.partner1_name} & ${invite.partner2_name}`;drawDestination()}
function drawDestination(){if(!settings)return;$('#paymentDestination').textContent=$('#paymentMethod').value==='instapay'?settings.instapay_handle:settings.vodafone_cash_number}
$('#paymentMethod').onchange=drawDestination;$('#receiptFile').onchange=e=>$('#receiptName').textContent=e.target.files?.[0]?.name||'';$('#copyPay').onclick=()=>navigator.clipboard?.writeText($('#paymentDestination').textContent);
async function boot(){({user}=await requireCustomer());if(!planSlug||!invitationId){location.href='builder.html';return}const activeMembership=await getActiveSubscription(user);if(activeMembership){location.href=`builder.html?id=${encodeURIComponent(invitationId)}&membership=active`;return}settings=await loadSettings();const dbPlans=await loadPlans();plan=(dbPlans||fallbackPlans).find(x=>x.slug===planSlug);if(!plan)throw new Error('Plan not found');const sb=await getSupabase();if(!sb){invite=getDemoInvitationById(invitationId)||{partner1_name:'Ahmed',partner2_name:'Salma',id:invitationId||'demo-invite'};render();return}const {data,error}=await sb.from('invitations').select('*').eq('id',invitationId).single();if(error)throw error;invite=data;if(invite.status==='active'&&!invite.is_trial){location.href='dashboard.html';return}const {data:pending}=await sb.from('orders').select('*').eq('invitation_id',invitationId).eq('status','pending_review').maybeSingle();if(pending){showSuccess(pending.id);$('#checkoutForm').hidden=true}render()}
function showSuccess(id){const l=getLang();const box=$('#orderSuccess');box.hidden=false;box.className='order-success';box.innerHTML=`<small>${t('checkout_pending',l)}</small><strong>#${String(id).slice(0,8).toUpperCase()}</strong><p>${l==='ar'?'هتلاقي حالة الطلب في لوحة حسابك، وبعد اعتماد الإدارة يتفعّل رابط الدعوة.':'Track the order in your dashboard. The invitation goes live after admin approval.'}</p><a class="btn btn-primary" href="dashboard.html">${t('dashboard_title',l)}</a>`}
$('#checkoutForm').onsubmit=async e=>{e.preventDefault();const file=$('#receiptFile').files?.[0];if(!file)return;const btn=$('#paySubmit');btn.disabled=true;try{if(!(await getSupabase())){const id=crypto.randomUUID();localStorage.setItem('wedora_demo_order',JSON.stringify({id,plan,invite,status:'pending_review'}));showSuccess(id);e.currentTarget.hidden=true;return}const sb=await getSupabase();const receiptPath=await uploadFile('payment-receipts',file,`${user.id}/${invitationId}`,{publicFile:false});const {data,error}=await sb.from('orders').insert({user_id:user.id,invitation_id:invitationId,plan_id:plan.id,amount:plan.price,currency:settings.currency||'EGP',payment_method:$('#paymentMethod').value,receipt_path:receiptPath,transfer_reference:$('#transferReference').value.trim()||null,status:'pending_review'}).select('*').single();if(error)throw error;showSuccess(data.id);e.currentTarget.hidden=true}catch(err){$('#checkoutMsg').className='error';$('#checkoutMsg').textContent=err.message||String(err)}finally{btn.disabled=false}};window.addEventListener('wedora:language',render);boot().catch(e=>{$('#checkoutMsg').className='error';$('#checkoutMsg').textContent=e.message});
